### ISSUE TITLE
Improvement? use pd.read_sql instead of pd.DataFrame(cur.fetchall()))

### ISSUE THREAD

**Issue by climatebrad** [learn-co-curriculum/dsc-selecting-data#1]
Multiple examples use the syntax

```
cur.execute(q)
df = pd.DataFrame(cur.fetchall())
df.columns = [x[0] for x in cur.description]
```

(where q is the sql query string) 

which adds the column names after the creation of the dataframe.

This could be replaced by the more concise and intuitive:

```
df = pd.read_sql(q, conn)
```

(Alternatively, one could do:

```
df = pd.DataFrame(cur.fetchall()),columns = [x[0] for x in cur.description])
```

but that's not as much of an improvement)

**Comment by hoffm386** [comment]
Hi @climatebrad, thanks for flagging!

The latest version has been updated so that it explains how to use the cursor but then uses the more concise syntax afterwards
