### ISSUE TITLE
Picture and database mismatch

### ISSUE THREAD

**Issue by andrwprk** [learn-co-curriculum/dsc-selecting-data#2]
the picture in "selecting data" section with the database showing rings as "no" or "yes" is wrong. It is actually stored as an int, "0" or "1"

This made the last part of the lab not work until I checked how the entire database was stored since rings were not checked until that last part. 

Unless that's part of the lesson you were trying to teach I suppose.

**Comment by hoffm386** [comment]
Hi @andrwprk, I think you are referring to the [lab associated with this lesson](https://github.com/learn-co-curriculum/dsc-selecting-data-lab)

This discrepancy has been clarified with the latest updates to that lab. Thanks!
